# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=16, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('created_at', models.DateField(verbose_name='Created at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('num_members', models.PositiveIntegerField(default=0, verbose_name='Number of members')),
                ('topic', models.CharField(max_length=1024, verbose_name='Topic')),
                ('purpose', models.CharField(max_length=1024, verbose_name='Purpose')),
                ('fetched_at', models.DateField(auto_now=True, verbose_name='Fetched at')),
            ],
            options={
                'verbose_name': 'Channel',
                'ordering': ('is_archived', 'name'),
            },
        ),
    ]
